"""
Test script for FashionCLIP embeddings and color extraction.

Processes local cropped images (if available) through the full feature 
extraction pipeline and validates the outputs like cosine similarity
bounds and dominant color naming.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import numpy as np
from PIL import Image

# Add project root to path
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from wardrobe.item_processor import WardrobeProcessor
from wardrobe.embeddings import ClothingEmbedder


def main():
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    
    # 1. Gather test images
    # We will use the transparent crops generated by the segmentation test
    # to ensure realistic data matches. If not found, skip.
    crops_dir = project_root / "tests" / "output" / "crops"
    
    if not crops_dir.exists():
        print(f"Error: No crops found in {crops_dir}.")
        print("Please run test_segmentation.py first to generate cropped test items.")
        sys.exit(1)
        
    image_paths = sorted(list(crops_dir.glob("*.png")))[:6]  # Test up to 6 items
    
    if len(image_paths) < 2:
        print("Need at least 2 cropped images to test similarities.")
        sys.exit(1)
        
    print(f"Testing {len(image_paths)} local crop images...")
    
    # 2. Initialize Processor (CPU)
    processor = WardrobeProcessor(embedder_device="cpu")
    
    embeddings = []
    item_names = []
    all_results = []
    
    print("\n" + "="*60)
    print("  Extracting Colors and Embeddings")
    print("="*60)
    
    for path in image_paths:
        img = Image.open(path)
        
        # We manually process it like the segmenter would
        result = processor.process_item(
            cropped_image=img, 
            label="test_item", 
            category=path.name.split("_")[-1].replace(".png", "") # e.g. "top"
        )
        all_results.append(result)
        
        print(f"\nItem: {path.name}")
        
        # Display dominant colors
        colors = result["dominant_colors"]
        print("  Dominant Colors:")
        for i, (name, pct) in enumerate(zip(colors["color_names"], colors["percentages"])):
            print(f"    - {name}: {pct*100:.1f}%")
            
        emb = result["embedding"]
        embeddings.append(emb)
        item_names.append(path.stem[:15] + "...")
        print(f"  Embedding Shape: {emb.shape}")
        
    # 3. Similarity Matrix
    print("\n" + "="*60)
    print("  Cosine Similarity Matrix")
    print("="*60)
    
    emb_matrix = np.array(embeddings)
    sim_matrix = ClothingEmbedder.compute_similarity_matrix(emb_matrix, emb_matrix)
    
    # Print header
    header = " " * 18 + "".join([f"{name[:10]:>12}" for name in item_names])
    print(header)
    
    # Print rows
    for i, name1 in enumerate(item_names):
        row_str = f"{name1:>16}  "
        for j in range(len(item_names)):
            score = sim_matrix[i, j]
            row_str += f"{score:>12.3f}"
        print(row_str)

    # 4. Generate Visual Summary Image
    print("\n" + "="*60)
    print("  Generating Visual Summary Image")
    print("="*60)
    
    try:
        import matplotlib.pyplot as plt
        import matplotlib.patches as patches
        
        num_items = len(image_paths)
        fig, axes = plt.subplots(num_items, 2, figsize=(10, 3 * num_items))
        
        # If there's only 1 item, axes is 1D array. Make it 2D for consistency
        if num_items == 1:
            axes = np.array([axes])
            
        fig.suptitle("Wardrobe Feature Extraction Summary", fontsize=16)
        
        for i, path in enumerate(image_paths):
            # Load and display crop
            img = Image.open(path)
            ax_img = axes[i, 0]
            ax_img.imshow(img)
            ax_img.axis('off')
            ax_img.set_title(f"Crop: {path.name}", fontsize=10)
            
            # Display colors 
            ax_color = axes[i, 1]
            ax_color.axis('off')
            ax_color.set_xlim(0, 1)
            ax_color.set_ylim(0, 1)
            ax_color.set_title("Dominant Colors Extracted", fontsize=10)
            
            # Fetch our pre-processed colors for this item
            colors = all_results[i]["dominant_colors"]
            
            # Draw color swatches
            y_pos = 0.8
            for j, (rgb, name, pct) in enumerate(zip(colors["colors_rgb"], colors["color_names"], colors["percentages"])):
                # Normalize RGB for matplotlib (0-1)
                normalized_rgb = (rgb[0]/255, rgb[1]/255, rgb[2]/255)
                
                # Draw square swatch
                rect = patches.Rectangle((0.1, y_pos - 0.1), 0.2, 0.2, facecolor=normalized_rgb, edgecolor='black', linewidth=1)
                ax_color.add_patch(rect)
                
                # Add text label
                ax_color.text(0.35, y_pos, f"{name} ({pct*100:.1f}%)", verticalalignment='center', fontsize=12)
                
                y_pos -= 0.3
                
        plt.tight_layout()
        out_path = project_root / "tests" / "output" / "visual_summary.png"
        plt.savefig(out_path, dpi=150, bbox_inches='tight')
        plt.close()
        
        print(f"Visual summary saved successfully: {out_path}")
    except ImportError:
        print("matplotlib not installed, skipping visual summary rendering.")

    print("\nValidation Complete!")


if __name__ == "__main__":
    main()
