"""phase 2: drop weather fields, add trends/recommendations/uploads

Revision ID: bcf6ef67e0c8
Revises: c292b4307129
Create Date: 2026-04-23 23:49:13.221341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf6ef67e0c8'
down_revision: Union[str, None] = 'c292b4307129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('dominant_colors', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index(op.f('ix_trends_id'), 'trends', ['id'], unique=False)
    op.create_index(op.f('ix_trends_source'), 'trends', ['source'], unique=False)
    op.create_table('outfit_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_recommendations_id'), 'outfit_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_outfit_recommendations_trend_id'), 'outfit_recommendations', ['trend_id'], unique=False)
    op.create_index(op.f('ix_outfit_recommendations_user_id'), 'outfit_recommendations', ['user_id'], unique=False)
    op.create_table('wardrobe_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wardrobe_uploads_id'), 'wardrobe_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_wardrobe_uploads_user_id'), 'wardrobe_uploads', ['user_id'], unique=False)
    op.create_table('buy_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('desired_colors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['outfit_recommendations.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buy_recommendations_id'), 'buy_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_buy_recommendations_recommendation_id'), 'buy_recommendations', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_buy_recommendations_trend_id'), 'buy_recommendations', ['trend_id'], unique=False)
    op.create_index(op.f('ix_buy_recommendations_user_id'), 'buy_recommendations', ['user_id'], unique=False)
    op.create_table('outfit_recommendation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('wardrobe_item_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['outfit_recommendations.id'], ),
    sa.ForeignKeyConstraint(['wardrobe_item_id'], ['wardrobe_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_recommendation_items_id'), 'outfit_recommendation_items', ['id'], unique=False)
    op.create_index(op.f('ix_outfit_recommendation_items_recommendation_id'), 'outfit_recommendation_items', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_outfit_recommendation_items_wardrobe_item_id'), 'outfit_recommendation_items', ['wardrobe_item_id'], unique=False)
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'location_name')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'season')
    op.add_column('wardrobe_items', sa.Column('upload_id', sa.Integer(), nullable=True))
    op.add_column('wardrobe_items', sa.Column('subcategory', sa.String(), nullable=True))
    op.add_column('wardrobe_items', sa.Column('source', sa.String(), nullable=False, server_default='uploaded'))
    op.add_column('wardrobe_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_wardrobe_items_upload_id'), 'wardrobe_items', ['upload_id'], unique=False)
    op.create_index(op.f('ix_wardrobe_items_user_id'), 'wardrobe_items', ['user_id'], unique=False)
    op.create_foreign_key(None, 'wardrobe_items', 'wardrobe_uploads', ['upload_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wardrobe_items', type_='foreignkey')
    op.drop_index(op.f('ix_wardrobe_items_user_id'), table_name='wardrobe_items')
    op.drop_index(op.f('ix_wardrobe_items_upload_id'), table_name='wardrobe_items')
    op.drop_column('wardrobe_items', 'created_at')
    op.drop_column('wardrobe_items', 'source')
    op.drop_column('wardrobe_items', 'subcategory')
    op.drop_column('wardrobe_items', 'upload_id')
    op.add_column('users', sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('location_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_outfit_recommendation_items_wardrobe_item_id'), table_name='outfit_recommendation_items')
    op.drop_index(op.f('ix_outfit_recommendation_items_recommendation_id'), table_name='outfit_recommendation_items')
    op.drop_index(op.f('ix_outfit_recommendation_items_id'), table_name='outfit_recommendation_items')
    op.drop_table('outfit_recommendation_items')
    op.drop_index(op.f('ix_buy_recommendations_user_id'), table_name='buy_recommendations')
    op.drop_index(op.f('ix_buy_recommendations_trend_id'), table_name='buy_recommendations')
    op.drop_index(op.f('ix_buy_recommendations_recommendation_id'), table_name='buy_recommendations')
    op.drop_index(op.f('ix_buy_recommendations_id'), table_name='buy_recommendations')
    op.drop_table('buy_recommendations')
    op.drop_index(op.f('ix_wardrobe_uploads_user_id'), table_name='wardrobe_uploads')
    op.drop_index(op.f('ix_wardrobe_uploads_id'), table_name='wardrobe_uploads')
    op.drop_table('wardrobe_uploads')
    op.drop_index(op.f('ix_outfit_recommendations_user_id'), table_name='outfit_recommendations')
    op.drop_index(op.f('ix_outfit_recommendations_trend_id'), table_name='outfit_recommendations')
    op.drop_index(op.f('ix_outfit_recommendations_id'), table_name='outfit_recommendations')
    op.drop_table('outfit_recommendations')
    op.drop_index(op.f('ix_trends_source'), table_name='trends')
    op.drop_index(op.f('ix_trends_id'), table_name='trends')
    op.drop_table('trends')
    # ### end Alembic commands ###
